apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: voluntary-moth-java-quarkus
  janus-idp.io/tekton: voluntary-moth-java-quarkus
  backstage.io/kubernetes-id: voluntary-moth-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: voluntary-moth-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
